intel_extraction_prompt: |
  You are a cybersecurity analyst.
  Extract key information from the following CVE description.

  Input: {raw_cve_data}

  Output JSON format:
  {
    "cve_id": "CVE-XXXX-XXXXX",
    "summary": "...",
    "cvss_score": float or "N/A"
  }

threat_scoring_prompt: |
  You are a senior threat intelligence analyst.
  Analyze the following CVE details and provide a threat score.

  Input: {extracted_cve_data}

  Output JSON format:
  {
    "risk_level": "Critical/High/Medium/Low",
    "exploit_likelihood": "High/Medium/Low",
    "recommendation": "..."
  }